[package]
name = "rust-api"
version = "0.0.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.13", features = ["json"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde_json = { version = "1.0.89", features = ["preserve_order"] }
