[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.12"
rocket = "0.5.0-rc.2"
uuid = { version = "1.2.1", features = ["v4"] }
